model_ema: True
criterion: CrossEntropyLoss
optimizer: 
  name: adam # adamw, adam, sgd
  lr: 2e-3
  weight_decay: 0
  momentum: 0.9
  clipping: True
scheduler:
  name: CosineAnnealingLR
  min_lr: 2e-7
  # name: ReduceLROnPlateau
  # lr_factor: 0.5
  # patience: 5
  warmup: False
