_target_: src.models.your_model.CustomModel

# params of model class __init__ function
input_dim: 13
vocab_size: 30 # len(LETTER_LIST)
encoder_hidden_dim: 256
decoder_hidden_dim: 512
embed_dim: 256
key_value_size: 128
teacher_forcing_schedule: True